export const USER_DATA = [
    {
        id: 1,
        fullName: "Nguyễn Văn A",
        companyName: "Công ty TNHH ABC",
        email: "nguyenvana@example.com",
        phone: "0987654321",
        address: "123 Đường Lê Lợi, Quận 1, TP.HCM",
        joinDate: "2024-01-15",
        group: "Doanh Nhân Trẻ",
        score: 85,
        role: "user",
    },
    {
        id: 2,
        fullName: "Trần Thị B",
        companyName: "Công ty CP XYZ",
        email: "tranthib@example.com",
        phone: "0976543210",
        address: "45 Phố Huế, Hai Bà Trưng, Hà Nội",
        joinDate: "2023-12-20",
        group: "Khởi Nghiệp",
        score: 92,
        role: "admin",
    },
    {
        id: 3,
        fullName: "Lê Văn C",
        companyName: "Tập đoàn DEF",
        email: "levanc@example.com",
        phone: "0912345678",
        address: "789 Nguyễn Trãi, Quận 5, TP.HCM",
        joinDate: "2024-02-10",
        group: "Công Nghệ",
        score: 78,
        role: "user",
    },
    {
        id: 4,
        fullName: "Phạm Thị D",
        companyName: "Startup GHI",
        email: "phamthid@example.com",
        phone: "0909876543",
        address: "56 Trần Hưng Đạo, Đống Đa, Hà Nội",
        joinDate: "2024-03-05",
        group: "Nữ Doanh Nhân",
        score: 95,
        role: "superadmin",
    },
    {
        id: 5,
        fullName: "Hoàng Văn E",
        companyName: "Công ty TNHH JKL",
        email: "hoangvane@example.com",
        phone: "0934567890",
        address: "12 Nguyễn Du, Quận 3, TP.HCM",
        joinDate: "2023-11-30",
        group: "Xây Dựng",
        score: 80,
        role: "user",
    },
    {
        id: 6,
        fullName: "Đặng Thị F",
        companyName: "Công ty CP MNO",
        email: "dangthif@example.com",
        phone: "0923456789",
        address: "67 Lý Thường Kiệt, Ba Đình, Hà Nội",
        joinDate: "2024-02-22",
        group: "Tài Chính",
        score: 88,
        role: "admin",
    },
    {
        id: 7,
        fullName: "Vũ Minh G",
        companyName: "Tập đoàn PQR",
        email: "vuminhg@example.com",
        phone: "0911223344",
        address: "34 Pasteur, Quận 1, TP.HCM",
        joinDate: "2024-01-05",
        group: "Marketing",
        score: 76,
        role: "user",
    },
    {
        id: 8,
        fullName: "Bùi Thị H",
        companyName: "Công ty CP STU",
        email: "buithih@example.com",
        phone: "0967888999",
        address: "99 Hai Bà Trưng, Cầu Giấy, Hà Nội",
        joinDate: "2023-12-10",
        group: "Y Tế",
        score: 90,
        role: "superadmin",
    },
    {
        id: 9,
        fullName: "Lâm Văn I",
        companyName: "Công ty TNHH VWX",
        email: "lamvani@example.com",
        phone: "0944332211",
        address: "88 Phạm Ngọc Thạch, Quận 10, TP.HCM",
        joinDate: "2024-02-01",
        group: "Giáo Dục",
        score: 84,
        role: "user",
    },
    {
        id: 10,
        fullName: "Trịnh Thị J",
        companyName: "Tập đoàn YZA",
        email: "trinhthij@example.com",
        phone: "0955667788",
        address: "77 Lê Văn Sỹ, Tân Bình, TP.HCM",
        joinDate: "2023-11-25",
        group: "Du Lịch",
        score: 89,
        role: "admin",
    },
    {
        id: 11,
        fullName: "Đỗ Văn K",
        companyName: "Công ty TNHH BCD",
        email: "dovank@example.com",
        phone: "0977885566",
        address: "101 Hoàng Hoa Thám, Ba Đình, Hà Nội",
        joinDate: "2024-03-12",
        group: "Nông Nghiệp",
        score: 87,
        role: "user",
    },
    {
        id: 12,
        fullName: "Phan Thị L",
        companyName: "Công ty CP EFG",
        email: "phanthil@example.com",
        phone: "0988996655",
        address: "200 Lê Hồng Phong, Quận 5, TP.HCM",
        joinDate: "2023-12-05",
        group: "Thời Trang",
        score: 93,
        role: "superadmin",
    },
    {
        id: 13,
        fullName: "Trương Văn M",
        companyName: "Tập đoàn HIJ",
        email: "truongvanm@example.com",
        phone: "0991122334",
        address: "300 Võ Văn Kiệt, Quận 6, TP.HCM",
        joinDate: "2024-01-20",
        group: "Khoa Học",
        score: 82,
        role: "user",
    },
    {
        id: 14,
        fullName: "Hồ Thị N",
        companyName: "Công ty TNHH KLM",
        email: "hothin@example.com",
        phone: "0977334455",
        address: "400 Nguyễn Văn Linh, Quận 7, TP.HCM",
        joinDate: "2024-02-18",
        group: "Môi Trường",
        score: 79,
        role: "admin",
    },
    {
        id: 15,
        fullName: "Lương Văn O",
        companyName: "Công ty CP OPQ",
        email: "luongvano@example.com",
        phone: "0955443322",
        address: "500 Trường Chinh, Tân Phú, TP.HCM",
        joinDate: "2024-03-08",
        group: "Giao Thông",
        score: 86,
        role: "user",
    },
    {
        id: 16,
        fullName: "Ngô Thị P",
        companyName: "Tập đoàn RST",
        email: "ngothip@example.com",
        phone: "0922113344",
        address: "600 Xô Viết Nghệ Tĩnh, Bình Thạnh, TP.HCM",
        joinDate: "2023-11-18",
        group: "Công Nghệ Sinh Học",
        score: 91,
        role: "superadmin",
    },
    {
        id: 17,
        fullName: "Tô Văn Q",
        companyName: "Công ty TNHH UVW",
        email: "tovanq@example.com",
        phone: "0912345566",
        address: "700 Lý Chính Thắng, Quận 3, TP.HCM",
        joinDate: "2024-02-25",
        group: "Bất Động Sản",
        score: 77,
        role: "user",
    },
    {
        id: 18,
        fullName: "Trần Thị R",
        companyName: "Công ty CP XYZ",
        email: "tranthir@example.com",
        phone: "0909988776",
        address: "800 Nguyễn Đình Chiểu, Quận 1, TP.HCM",
        joinDate: "2024-01-28",
        group: "Năng Lượng",
        score: 94,
        role: "admin",
    },
];
