export const USER_DATA = [
  {
    id: 1,
    fullName: "Nguyễn Văn A",
    companyName: "Công ty TNHH ABC",
    email: "nguyenvana@example.com",
    phone: "0987654321",
    address: "123 Đường Lê Lợi, Quận 1, TP.HCM",
    joinDate: "2024-01-15",
    group: "Doanh Nhân Trẻ",
    score: 85,
  },
  {
    id: 2,
    fullName: "Trần Thị B",
    companyName: "Công ty CP XYZ",
    email: "tranthib@example.com",
    phone: "0976543210",
    address: "45 Phố Huế, Hai Bà Trưng, Hà Nội",
    joinDate: "2023-12-20",
    group: "Khởi Nghiệp",
    score: 92,
  },
  {
    id: 3,
    fullName: "Lê Văn C",
    companyName: "Tập đoàn DEF",
    email: "levanc@example.com",
    phone: "0912345678",
    address: "789 Nguyễn Trãi, Quận 5, TP.HCM",
    joinDate: "2024-02-10",
    group: "Công Nghệ",
    score: 78,
  },
  {
    id: 4,
    fullName: "Phạm Thị D",
    companyName: "Startup GHI",
    email: "phamthid@example.com",
    phone: "0909876543",
    address: "56 Trần Hưng Đạo, Đống Đa, Hà Nội",
    joinDate: "2024-03-05",
    group: "Nữ Doanh Nhân",
    score: 95,
  },
  {
    id: 5,
    fullName: "Hoàng Văn E",
    companyName: "Công ty TNHH JKL",
    email: "hoangvane@example.com",
    phone: "0934567890",
    address: "12 Nguyễn Du, Quận 3, TP.HCM",
    joinDate: "2023-11-30",
    group: "Xây Dựng",
    score: 80,
  },
  {
    id: 6,
    fullName: "Đặng Thị F",
    companyName: "Công ty CP MNO",
    email: "dangthif@example.com",
    phone: "0923456789",
    address: "67 Lý Thường Kiệt, Ba Đình, Hà Nội",
    joinDate: "2024-02-22",
    group: "Tài Chính",
    score: 88,
  },
  {
    id: 7,
    fullName: "Vũ Minh G",
    companyName: "Tập đoàn PQR",
    email: "vuminhg@example.com",
    phone: "0911223344",
    address: "34 Pasteur, Quận 1, TP.HCM",
    joinDate: "2024-01-05",
    group: "Marketing",
    score: 76,
  },
  {
    id: 8,
    fullName: "Bùi Thị H",
    companyName: "Công ty CP STU",
    email: "buithih@example.com",
    phone: "0967888999",
    address: "99 Hai Bà Trưng, Cầu Giấy, Hà Nội",
    joinDate: "2023-12-10",
    group: "Y Tế",
    score: 90,
  },
  {
    id: 9,
    fullName: "Lâm Văn I",
    companyName: "Công ty TNHH VWX",
    email: "lamvani@example.com",
    phone: "0944332211",
    address: "88 Phạm Ngọc Thạch, Quận 10, TP.HCM",
    joinDate: "2024-02-01",
    group: "Giáo Dục",
    score: 84,
  },
  {
    id: 10,
    fullName: "Trịnh Thị J",
    companyName: "Tập đoàn YZA",
    email: "trinhthij@example.com",
    phone: "0955667788",
    address: "77 Lê Văn Sỹ, Tân Bình, TP.HCM",
    joinDate: "2023-11-25",
    group: "Du Lịch",
    score: 89,
  },
  {
    id: 11,
    fullName: "Đỗ Văn K",
    companyName: "Công ty TNHH BCD",
    email: "dovank@example.com",
    phone: "0977885566",
    address: "101 Hoàng Hoa Thám, Ba Đình, Hà Nội",
    joinDate: "2024-03-12",
    group: "Nông Nghiệp",
    score: 87,
  },
  {
    id: 12,
    fullName: "Phan Thị L",
    companyName: "Công ty CP EFG",
    email: "phanthil@example.com",
    phone: "0988996655",
    address: "200 Lê Hồng Phong, Quận 5, TP.HCM",
    joinDate: "2023-12-05",
    group: "Thời Trang",
    score: 93,
  },
  {
    id: 13,
    fullName: "Trương Văn M",
    companyName: "Tập đoàn HIJ",
    email: "truongvanm@example.com",
    phone: "0991122334",
    address: "300 Võ Văn Kiệt, Quận 6, TP.HCM",
    joinDate: "2024-01-20",
    group: "Khoa Học",
    score: 82,
  },
  {
    id: 14,
    fullName: "Hồ Thị N",
    companyName: "Công ty TNHH KLM",
    email: "hothin@example.com",
    phone: "0977334455",
    address: "400 Nguyễn Văn Linh, Quận 7, TP.HCM",
    joinDate: "2024-02-18",
    group: "Môi Trường",
    score: 79,
  },
  {
    id: 15,
    fullName: "Lương Văn O",
    companyName: "Công ty CP OPQ",
    email: "luongvano@example.com",
    phone: "0955443322",
    address: "500 Trường Chinh, Tân Phú, TP.HCM",
    joinDate: "2024-03-08",
    group: "Giao Thông",
    score: 86,
  },
  {
    id: 16,
    fullName: "Ngô Thị P",
    companyName: "Tập đoàn RST",
    email: "ngothip@example.com",
    phone: "0922113344",
    address: "600 Xô Viết Nghệ Tĩnh, Bình Thạnh, TP.HCM",
    joinDate: "2023-11-18",
    group: "Công Nghệ Sinh Học",
    score: 91,
  },
  {
    id: 17,
    fullName: "Tô Văn Q",
    companyName: "Công ty TNHH UVW",
    email: "tovanq@example.com",
    phone: "0912345566",
    address: "700 Lý Chính Thắng, Quận 3, TP.HCM",
    joinDate: "2024-02-25",
    group: "Bất Động Sản",
    score: 77,
  },
  {
    id: 18,
    fullName: "Trần Thị R",
    companyName: "Công ty CP XYZ",
    email: "tranthir@example.com",
    phone: "0909988776",
    address: "800 Nguyễn Đình Chiểu, Quận 1, TP.HCM",
    joinDate: "2024-01-28",
    group: "Năng Lượng",
    score: 94,
  },
];

export const EVENT_DATA = [
  {
    id: 1,
    name: "Hội Thảo Công Nghệ 2025",
    organizer: "Tech Innovators",
    location: "Trung tâm Hội nghị Quốc gia, Hà Nội",
    date: "2025-06-15",
    time: "09:00",
    description:
      "Sự kiện quy tụ các chuyên gia công nghệ hàng đầu, chia sẻ về AI, Blockchain, và IoT.",
    status: "upcoming",
  },
  {
    id: 2,
    name: "Gala Doanh Nhân Trẻ",
    organizer: "Hiệp hội Doanh Nhân Trẻ",
    location: "Khách sạn Vinpearl, TP. Hồ Chí Minh",
    date: "2025-07-20",
    time: "19:00",
    description:
      "Sự kiện kết nối và tôn vinh các doanh nhân trẻ có thành tựu xuất sắc.",
    status: "upcoming",
  },
  {
    id: 3,
    name: "Workshop Lập Trình Web",
    organizer: "Coder Academy",
    location: "Trường Đại học Bách Khoa",
    date: "2025-05-10",
    time: "14:00",
    description:
      "Buổi workshop hướng dẫn cách xây dựng một trang web hiện đại bằng Next.js và Tailwind CSS.",
    status: "completed",
  },
  {
    id: 4,
    name: "Ngày Hội Tuyển Dụng 2025",
    organizer: "HR Connect",
    location: "Trung tâm Triển lãm SECC",
    date: "2025-09-05",
    time: "10:00",
    description:
      "Cơ hội kết nối với hơn 100 doanh nghiệp hàng đầu đang tuyển dụng.",
    status: "upcoming",
  },
  {
    id: 5,
    name: "Giải Marathon Thành Phố",
    organizer: "Liên đoàn Thể thao",
    location: "Quận 1, TP. Hồ Chí Minh",
    date: "2025-04-22",
    time: "06:00",
    description:
      "Sự kiện chạy bộ quy mô lớn với nhiều cự ly khác nhau dành cho mọi đối tượng.",
    status: "completed",
  },
  {
    id: 6,
    name: "Hội Chợ Du Lịch Quốc Tế",
    organizer: "Hiệp hội Du lịch",
    location: "Cung Văn Hóa Hữu Nghị, Hà Nội",
    date: "2025-08-12",
    time: "08:00",
    description:
      "Triển lãm giới thiệu các điểm đến hấp dẫn và dịch vụ du lịch chất lượng.",
    status: "upcoming",
  },
  {
    id: 7,
    name: "Diễn Đàn Kinh Tế 2025",
    organizer: "Bộ Kế hoạch và Đầu tư",
    location: "Trung tâm Hội nghị Quốc tế",
    date: "2025-10-01",
    time: "09:00",
    description:
      "Sự kiện thảo luận về các xu hướng kinh tế và chính sách đầu tư.",
    status: "upcoming",
  },
  {
    id: 8,
    name: "Hội Nghị Bảo Mật Thông Tin",
    organizer: "Cyber Security Group",
    location: "Trung tâm Công nghệ Số, Đà Nẵng",
    date: "2025-11-15",
    time: "10:00",
    description:
      "Hội nghị dành cho các chuyên gia bảo mật để thảo luận về an toàn thông tin và phòng chống tấn công mạng.",
    status: "ongoing",
  },
];

export const NOTIF_DATA = [
  {
    id: 1,
    title: "Bảo trì hệ thống",
    content: "Hệ thống sẽ bảo trì vào ngày 20/03/2025.",
    type: "warning",
    createdAt: "2025-03-17",
    status: "active",
    targetAudience: ["all_users"],
  },
  {
    id: 2,
    title: "Khuyến mãi tháng 3",
    content: "Giảm 20% khi đăng ký gói Premium trước 31/03/2025.",
    type: "info",
    createdAt: "2025-03-15",
    status: "active",
    targetAudience: ["members"],
  },
  {
    id: 3,
    title: "Sự kiện Công nghệ 2025",
    content: "Đăng ký tham gia hội nghị vào ngày 10/04/2025.",
    type: "info",
    createdAt: "2025-03-10",
    status: "expired",
    targetAudience: ["all_users", "sponsor"],
  },
  {
    id: 4,
    title: "Thông báo lỗi đăng nhập",
    content: "Chúng tôi đang xử lý lỗi đăng nhập của một số người dùng.",
    type: "error",
    createdAt: "2025-03-16",
    status: "active",
    targetAudience: ["all_users"],
  },
  {
    id: 5,
    title: "Chúc mừng VIP",
    content: "Bạn đã đạt cấp bậc VIP và nhận nhiều ưu đãi!",
    type: "success",
    createdAt: "2025-03-12",
    status: "active",
    targetAudience: ["vip_members"],
  },
  {
    id: 6,
    title: "Cập nhật phiên bản mới",
    content: "Ứng dụng sẽ có bản cập nhật vào ngày 22/03/2025.",
    type: "info",
    createdAt: "2025-03-18",
    status: "active",
    targetAudience: ["all_users"],
  },
  {
    id: 7,
    title: "Thay đổi chính sách",
    content: "Chính sách quyền riêng tư sẽ thay đổi từ 01/04/2025.",
    type: "warning",
    createdAt: "2025-03-14",
    status: "active",
    targetAudience: ["all_users"],
  },
  {
    id: 8,
    title: "Bảo trì máy chủ",
    content: "Dịch vụ sẽ tạm dừng từ ngày 25/03/2025.",
    type: "warning",
    createdAt: "2025-03-19",
    status: "active",
    targetAudience: ["all_users"],
  },
  {
    id: 9,
    title: "Tích điểm đổi quà",
    content: "Nhận quà tặng khi đạt 1000 điểm trước 31/03/2025.",
    type: "success",
    createdAt: "2025-03-11",
    status: "active",
    targetAudience: ["members"],
  },
  {
    id: 10,
    title: "Khuyến mãi đặc biệt",
    content: "Giảm giá 30% cho đơn hàng từ 500K vào ngày 28/03/2025.",
    type: "info",
    createdAt: "2025-03-13",
    status: "active",
    targetAudience: ["all_users"],
  },
  {
    id: 11,
    title: "Cảnh báo bảo mật",
    content: "Vui lòng đổi mật khẩu để đảm bảo an toàn tài khoản.",
    type: "warning",
    createdAt: "2025-03-09",
    status: "active",
    targetAudience: ["all_users"],
  },
  {
    id: 12,
    title: "Giới thiệu bạn bè",
    content: "Mời bạn bè và nhận ngay 50K vào tài khoản!",
    type: "success",
    createdAt: "2025-03-08",
    status: "active",
    targetAudience: ["all_users"],
  },
  {
    id: 13,
    title: "Cập nhật điều khoản",
    content: "Điều khoản dịch vụ sẽ thay đổi từ ngày 01/04/2025.",
    type: "info",
    createdAt: "2025-03-07",
    status: "active",
    targetAudience: ["all_users"],
  },
  {
    id: 14,
    title: "Sự kiện thể thao",
    content: "Đăng ký tham gia giải đấu bóng đá nội bộ!",
    type: "info",
    createdAt: "2025-03-06",
    status: "expired",
    targetAudience: ["all_users"],
  },
  {
    id: 15,
    title: "Tặng quà sinh nhật",
    content: "Chúc mừng sinh nhật! Nhận ngay quà đặc biệt.",
    type: "success",
    createdAt: "2025-03-05",
    status: "active",
    targetAudience: ["members"],
  },
  {
    id: 16,
    title: "Thông báo quan trọng",
    content: "Vui lòng cập nhật thông tin cá nhân trước 15/04/2025.",
    type: "warning",
    createdAt: "2025-03-04",
    status: "active",
    targetAudience: ["all_users"],
  },
  {
    id: 17,
    title: "Nhắc nhở thanh toán",
    content: "Hóa đơn tháng này của bạn đến hạn vào ngày 25/03/2025.",
    type: "warning",
    createdAt: "2025-03-03",
    status: "active",
    targetAudience: ["members"],
  },
  {
    id: 18,
    title: "Giải thưởng đặc biệt",
    content: "Tham gia minigame để có cơ hội nhận giải thưởng lớn!",
    type: "success",
    createdAt: "2025-03-02",
    status: "expired",
    targetAudience: ["all_users"],
  },
  {
    id: 19,
    title: "Chương trình từ thiện",
    content: "Đồng hành cùng chúng tôi trong chiến dịch thiện nguyện.",
    type: "info",
    createdAt: "2025-03-01",
    status: "active",
    targetAudience: ["all_users", "Vip"],
  },
  {
    id: 20,
    title: "Thử nghiệm tính năng mới",
    content: "Đăng ký trải nghiệm tính năng beta trước 10/04/2025.",
    type: "info",
    createdAt: "2025-02-28",
    status: "active",
    targetAudience: ["sponsor"],
  },
];
export const FEE_DATA = [
  {
    id: "1", // Thêm trường key/id duy nhất
    name: "Nguyễn Văn A",
    phone: "0123456789",
    branch: { name: "Chi hội 1" },
    fees: {
      2023: "Đã đóng",
      2024: "Chưa đóng",
      2025: "Chưa đóng",
    },
  },
  {
    id: "2", // Thêm trường key/id duy nhất
    name: "Trần Thị B",
    phone: "0987654321",
    branch: { name: "Chi hội 2" },
    fees: {},
  },
];

export const TICKET_DATA = [
  {
    id: "TCK001",
    nguoi_mua: "Nguyễn Văn A",
    su_kien: "Hòa nhạc Sơn Tùng",
    ngay_dien_ra: "15/04/2025",
    loai_ve: "VIP",
    gia_tien: 2500000,
    trang_thai: "Đã thanh toán",
  },
  {
    id: "TCK002",
    nguoi_mua: "Trần Thị B",
    su_kien: "Triển lãm nghệ thuật",
    ngay_dien_ra: "20/04/2025",
    loai_ve: "Thường",
    gia_tien: 150000,
    trang_thai: "Chưa thanh toán",
  },
  {
    id: "TCK003",
    nguoi_mua: "Lê Minh C",
    su_kien: "Trận đấu bóng đá",
    ngay_dien_ra: "25/04/2025",
    loai_ve: "Khán đài A",
    gia_tien: 800000,
    trang_thai: "Đã thanh toán",
  },
  {
    id: "TCK004",
    nguoi_mua: "Phạm Thị D",
    su_kien: "Hội thảo công nghệ",
    ngay_dien_ra: "10/05/2025",
    loai_ve: "Online",
    gia_tien: 300000,
    trang_thai: "Chưa thanh toán",
  },
  {
    id: "TCK005",
    nguoi_mua: "Hoàng Văn E",
    su_kien: "Liveshow Mỹ Tâm",
    ngay_dien_ra: "30/04/2025",
    loai_ve: "Đặc biệt",
    gia_tien: 1800000,
    trang_thai: "Đã thanh toán",
  },
];
export const NEWS_DATA = [
  {
    id: "1",
    imageSrc: "https://cdn0979.cdn4s.com/media/chen-logo-15_5.jpg",
    type: "Hội viên",
    title:
      "DỰ ÁN TÒA THÁP VĂN PHÒNG & CĂN HỘ KHÁCH SẠN TIG TOWER CHÍNH THỨC KHỞI CÔNG - ĐIỂM NHẤN ĐẦU TƯ CHIẾN LƯỢC CỦA TẬP ĐOÀN ĐẦU TƯ THĂNG LONG (Tig)",
    content:
      "Sáng ngày 25/02/2025, Tập đoàn Đầu tư Thăng Long (TIG) cùng Công ty Cổ phần BĐS Hoa Anh Đào (thành viên tập đoàn) đã chính thức khởi công dự án TIG Tower...",
    date: "13/03/2025",
    status: "Đã diễn ra",
    key: "1",
  },
  {
    id: "2",
    imageSrc:
      "https://cdn0979.cdn4s.com/thumbs/xDv-khoisac2025/Anh-su-kien/dsc_9773_thumb_500.jpg",
    type: "Tin tức - Sự kiện",
    title:
      "NGÀY HỘI KẾT NỐI KINH DOANH 2025: THÀNH CÔNG VỚI NHỮNG CON SỐ ẤN TƯỢNG",
    content:
      "Ngày 28/02/2025, tại Vườn Vua Resort & Villas, Phú Thọ, Hội Doanh nghiệp trẻ Hà Nội (HANOIBA) đã tổ chức thành công Ngày Hội Kết nối Kinh doanh 2025...",
    date: "05/03/2025",
    status: "Đã diễn ra",
    key: "2",
  },
  {
    id: "3",
    imageSrc:
      "https://cdn0979.cdn4s.com/thumbs/xDv-khoisac2025/Anh-su-kien/dsc_0125_thumb_500.jpg",
    type: "Tin tức - Sự kiện",
    title: "TOẠ ĐÀM ĐỐI THOẠI HÀ NỘI 2025: KỶ NGUYÊN MỚI - VẬN HỘI MỚI",
    content:
      "Chiều ngày 28/02, trong khuôn khổ của Xuân Đoàn viên 2025, HANOIBA đã tổ chức chương trình Toạ đàm Đối thoại Hà Nội 2025...",
    date: "06/03/2025",
    status: "Đã diễn ra",
    key: "3",
  },
  {
    id: "4",
    imageSrc: "https://cdn0979.cdn4s.com/media/chen-logo-16_5.jpg",
    type: "Hội viên",
    title: "TỌA ĐÀM CHUYÊN ĐỀ: CƠ HỘI ĐẦU TƯ BẤT ĐỘNG SẢN 2025",
    content:
      "Sáng ngày 10/03/2025, Hội Doanh nghiệp trẻ Hà Nội đã tổ chức tọa đàm chuyên đề 'Cơ hội đầu tư bất động sản 2025'...",
    date: "10/03/2025",
    status: "Đã diễn ra",
    key: "4",
  },
  {
    id: "5",
    imageSrc:
      "https://cdn0979.cdn4s.com/thumbs/xDv-khoisac2025/Anh-su-kien/dsc_0456_thumb_500.jpg",
    type: "Tin tức - Sự kiện",
    title: "DIỄN ĐÀN DOANH NGHIỆP VIỆT NAM 2025",
    content:
      "Diễn đàn Doanh nghiệp Việt Nam 2025 diễn ra vào ngày 15/03/2025 tại TP. Hồ Chí Minh với sự tham gia của hơn 500 lãnh đạo doanh nghiệp hàng đầu...",
    date: "15/03/2025",
    status: "Sắp diễn ra",
    key: "5",
  },
  {
    id: "6",
    imageSrc: "https://cdn0979.cdn4s.com/media/chen-logo-17_5.jpg",
    type: "Hội viên",
    title: "CÔNG BỐ QUỸ HỖ TRỢ KHỞI NGHIỆP 2025",
    content:
      "Hội Doanh nghiệp trẻ Hà Nội phối hợp với các quỹ đầu tư công bố Quỹ Hỗ trợ Khởi nghiệp 2025, với tổng vốn lên đến 100 tỷ đồng...",
    date: "18/03/2025",
    status: "Mới công bố",
    key: "6",
  },
  {
    id: "7",
    imageSrc:
      "https://cdn0979.cdn4s.com/thumbs/xDv-khoisac2025/Anh-su-kien/dsc_0987_thumb_500.jpg",
    type: "Tin tức - Sự kiện",
    title: "HỘI CHỢ KẾT NỐI CUNG CẦU 2025",
    content:
      "Hội chợ Kết nối Cung Cầu 2025 diễn ra tại Hà Nội từ ngày 20-22/03/2025, quy tụ hơn 1.000 gian hàng từ các doanh nghiệp trong và ngoài nước...",
    date: "20/03/2025",
    status: "Đang diễn ra",
    key: "7",
  },
  {
    id: "8",
    imageSrc:
      "https://cdn0979.cdn4s.com/thumbs/xDv-khoisac2025/Anh-su-kien/dsc_1123_thumb_500.jpg",
    type: "Hội viên",
    title: "LỄ RA MẮT CÂU LẠC BỘ DOANH NHÂN TRẺ 2025",
    content:
      "Ngày 22/03/2025, Hội Doanh nghiệp trẻ Hà Nội tổ chức lễ ra mắt CLB Doanh nhân trẻ 2025, quy tụ nhiều doanh nhân thành đạt...",
    date: "22/03/2025",
    status: "Sắp diễn ra",
    key: "8",
  },
  {
    id: "9",
    imageSrc:
      "https://cdn0979.cdn4s.com/thumbs/xDv-khoisac2025/Anh-su-kien/dsc_1321_thumb_500.jpg",
    type: "Tin tức - Sự kiện",
    title: "HỘI THẢO CHUYỂN ĐỔI SỐ TRONG KINH DOANH",
    content:
      "Hội thảo 'Chuyển đổi số trong kinh doanh' diễn ra vào ngày 25/03/2025 tại Đà Nẵng, với sự tham gia của các chuyên gia công nghệ...",
    date: "25/03/2025",
    status: "Mới công bố",
    key: "9",
  },
  {
    id: "10",
    imageSrc:
      "https://cdn0979.cdn4s.com/thumbs/xDv-khoisac2025/Anh-su-kien/dsc_1445_thumb_500.jpg",
    type: "Hội viên",
    title: "CHƯƠNG TRÌNH KẾT NỐI ĐẦU TƯ 2025",
    content:
      "Ngày 28/03/2025, Hội Doanh nghiệp trẻ Hà Nội tổ chức chương trình Kết nối Đầu tư 2025, tạo cầu nối giữa các nhà đầu tư và doanh nghiệp khởi nghiệp...",
    date: "28/03/2025",
    status: "Sắp diễn ra",
    key: "10",
  },
];
